#!/usr/bin/env bash
#
# install-git-hooks.sh: generate a stack-aware .pre-commit-config.yaml and install it.
#
# Uses the pre-commit framework (https://pre-commit.com): language-agnostic, one config,
# manages tool environments. Detects the stack and emits only the relevant repos/hooks.
# Backs up any existing config, then runs `pre-commit install` for the commit / commit-msg
# / pre-push stages if pre-commit is available.
#
# Pinned revs are current snapshots; run `pre-commit autoupdate` to refresh them.

set -uo pipefail

dir="${CLAUDE_PROJECT_DIR:-$PWD}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tags="$(bash "$here/detect-stack.sh" "$dir" 2>/dev/null || true)"
has() { printf '%s\n' "$tags" | grep -qx "$1"; }

cfg="$dir/.pre-commit-config.yaml"
if [ -f "$cfg" ]; then
  cp "$cfg" "$cfg.bak.$(date +%Y%m%d%H%M%S)"
  echo "Backed up existing .pre-commit-config.yaml"
fi

{
  echo "# Generated by agentic-setup stack-hooks. Detected: ${tags//$'\n'/ }"
  echo "# Refresh pinned revs with: pre-commit autoupdate"
  echo "repos:"

  # Cross-stack housekeeping (fast, language-agnostic).
  cat <<'YAML'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
YAML

  if has python; then
    cat <<'YAML'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
YAML
  fi

  if has swift; then
    cat <<'YAML'
  - repo: https://github.com/realm/SwiftLint
    rev: 0.57.1
    hooks:
      - id: swiftlint
        args: [--fix]
YAML
  fi

  # Node/TS: local hooks so we reuse the project's own installed toolchain.
  if has node; then
    echo "  - repo: local"
    echo "    hooks:"
    cat <<'YAML'
      - id: eslint
        name: eslint (changed files)
        entry: npx --no -- eslint --fix --no-warn-ignored
        language: system
        files: \.(ts|tsx|js|jsx|mjs|cjs)$
      - id: prettier
        name: prettier (changed files)
        entry: npx --no -- prettier --write --ignore-unknown
        language: system
        files: \.(ts|tsx|js|jsx|json|jsonc|css|scss|md|mdx|ya?ml|html|graphql)$
      - id: commitlint
        name: commitlint (conventional commits)
        entry: npx --no -- commitlint --edit
        language: system
        stages: [commit-msg]
        always_run: true
        pass_filenames: false
YAML
    if has ts; then
      cat <<'YAML'
      - id: tsc
        name: tsc --noEmit (typecheck)
        entry: npx --no -- tsc --noEmit
        language: system
        pass_filenames: false
        stages: [pre-push]
YAML
    fi
    if has convex; then
      cat <<'YAML'
      - id: convex-codegen
        name: convex codegen
        entry: npx --no -- convex codegen
        language: system
        pass_filenames: false
        stages: [pre-push]
YAML
    fi
  fi
} > "$cfg"

echo "Wrote $cfg"

if command -v pre-commit >/dev/null 2>&1; then
  ( cd "$dir" && pre-commit install && pre-commit install --hook-type commit-msg && pre-commit install --hook-type pre-push )
  echo "Installed git hooks (pre-commit, commit-msg, pre-push)."
  echo "Tip: run 'pre-commit run --all-files' once to baseline."
else
  echo "pre-commit not found. Install it, then run:"
  echo "  pre-commit install && pre-commit install --hook-type commit-msg && pre-commit install --hook-type pre-push"
  echo "  (uv tool install pre-commit  |  pipx install pre-commit  |  brew install pre-commit)"
fi

if has node; then
  echo "Node hooks use commitlint/eslint/prettier via npx; ensure they are project devDependencies:"
  echo "  npm i -D @commitlint/cli @commitlint/config-conventional eslint prettier"
  echo "  and a commitlint.config.js with: module.exports = { extends: ['@commitlint/config-conventional'] }"
fi
